FinalProject/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Data;

namespace FinalProject.Models
{
    public class Location
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public int ZIP { get; set; }
       

    }
}

FinalProject/ViewModels/AddLocationViewModel.cs
using FinalProject.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.ViewModels
{
    public class AddLocationViewModel : StatesListViewModel
    {

        [Required(ErrorMessage="You must enter a name for the location")]
        [Display(Name="Location Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter the Street Address")]
        [Display(Name = "Street Address")]
        public string Address { get; set; }

        [Required (ErrorMessage = "Please enter the City")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required (ErrorMessage = "Please enter the State")]
        [Display(Name = "State")]
        public string State { get; set; }

        [Required]
        public int ZIP { get; set; }
    }
}

FinalProject/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FinalProject.Data;
using FinalProject.Models;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.Web;
using Microsoft.AspNetCore.Authorization;


namespace FinalProject.Controllers
{   [Authorize]
    public class LocationController : Controller
    {
        private readonly ApplicationDbContext context;
        private CountyAPI CountyAPI;

        public LocationController(ApplicationDbContext dbContext)
        {
            context = dbContext;
            CountyAPI api = new CountyAPI();
            CountyAPI = api;
        }

        public IActionResult Index()
        {   
            decimal FedMinimumWage = 7.25m;
            List<Location> locations = context.Locations.ToList();
            List<WageLocation> wageLocations1 = context.WageLocations.ToList();
            List<int> locationIDs = context.Locations.Select(l => l.ID).ToList();
            // Checks to see if any locations need to be deleted from WageLocations Joined Table
            foreach (WageLocation wageLocation in wageLocations1)
            {
                if (!locationIDs.Contains(wageLocation.LocationID))
                {
                    context.WageLocations.Remove(wageLocation);
                    context.SaveChanges();
                }

            }

            foreach (Location location in locations)
                // Checks if existing locations in join table have been edited; saves the changes to the join table database
            {
                if (context.WageLocations.Where(wl => location.ID == wl.LocationID).Count() != 0)
                {

                    if (context.CityWages.Where(sw => sw.State == location.State).Where(sw => sw.City == location.City).Count() != 0)
                    {
                        WageLocation wageLocation = context.WageLocations.FirstOrDefault(wl => wl.LocationID == location.ID);
                        wageLocation.Wage = context.CityWages.Where(cw => cw.City == location.City).Select(cw => cw.MinWage).FirstOrDefault();
                        wageLocation.LocationID = location.ID;
                        wageLocation.LocationName = location.Name;
                        wageLocation.Address = location.Address;
                        wageLocation.City = location.City;
                        wageLocation.County = location.County;
                        wageLocation.State = location.State;
                        wageLocation.ZIP = location.ZIP;
                        context.SaveChanges();
                    }

                    else if (context.CountyWages.Where(ctw => ctw.County == location.County).Where(ctw => ctw.State == location.State).Count() != 0)
                    {
                        WageLocation wageLocation = context.WageLocations.FirstOrDefault(wl => wl.LocationID == location.ID);
                        wageLocation.Wage = context.CountyWages.Where(ctw => ctw.County == location.County).Select(ctw => ctw.MinWage).FirstOrDefault();
                        wageLocation.LocationID = location.ID;
                        wageLocation.LocationName = location.Name;
                        wageLocation.Address = location.Address;
                        wageLocation.City = location.City;
                        wageLocation.County = location.County;
                        wageLocation.State = location.State;
                        wageLocation.ZIP = location.ZIP;
                        context.SaveChanges();
                    }
                    else if (context.StateWages.Where(sw => sw.State == location.State).Count() != 0)
                    {
                        WageLocation wageLocation = context.WageLocations.FirstOrDefault(wl => wl.LocationID == location.ID);
                        wageLocation.Wage = context.StateWages.Where(sw => sw.State == location.State).Select(sw => sw.MinWage).FirstOrDefault();
                        wageLocation.LocationID = location.ID;
                        wageLocation.LocationName = location.Name;
                        wageLocation.Address = location.Address;
                        wageLocation.City = location.City;
                        wageLocation.County = location.County;
                        wageLocation.State = location.State;
                        wageLocation.ZIP = location.ZIP;
                        context.SaveChanges();
                    }

                    else
                    {
                        WageLocation wageLocation = context.WageLocations.FirstOrDefault(wl => wl.LocationID == location.ID);
                        wageLocation.Wage = FedMinimumWage;
                        wageLocation.LocationID = location.ID;
                        wageLocation.LocationName = location.Name;
                        wageLocation.Address = location.Address;
                        wageLocation.City = location.City;
                        wageLocation.County = location.County;
                        wageLocation.State = location.State;
                        wageLocation.ZIP = location.ZIP;
                        context.SaveChanges();
                    }
                }
                // Adds new rows to join table and collects the correct minimum wage
                else
                {
                    if (context.CityWages.Where(sw => sw.State == location.State).Where(sw => sw.City == location.City).Count() != 0)
                    {
                        WageLocation wageLocation = new WageLocation
                        {
                            Wage = context.CityWages.Where(cw => cw.City == location.City).Select(cw => cw.MinWage).FirstOrDefault(),
                            LocationID = location.ID,
                            LocationName = location.Name,
                            Address = location.Address,
                            City = location.City,
                            County = location.County,
                            State = location.State,
                            ZIP = location.ZIP
                        };
                        context.WageLocations.Add(wageLocation);
                        context.SaveChanges();
                    }

                    else if (context.CountyWages.Where(ctw => ctw.County == location.County).Where(ctw => ctw.State == location.State).Count() != 0)
                    {
                        WageLocation wageLocation = new WageLocation
                        {
                            Wage = context.CountyWages.Where(ctw => ctw.County == location.County).Select(ctw => ctw.MinWage).FirstOrDefault(),
                            LocationID = location.ID,
                            LocationName = location.Name,
                            Address = location.Address,
                            City = location.City,
                            County = location.County,
                            State = location.State,
                            ZIP = location.ZIP
                        };
                        context.WageLocations.Add(wageLocation);
                        context.SaveChanges();
                    }
                    else if (context.StateWages.Where(sw => sw.State == location.State).Count() != 0)
                    {
                        WageLocation wageLocation = new WageLocation
                        {
                            Wage = context.StateWages.Where(sw => sw.State == location.State).Select(sw => sw.MinWage).FirstOrDefault(),
                            LocationID = location.ID,
                            LocationName = location.Name,
                            Address = location.Address,
                            City = location.City,
                            County = location.County,
                            State = location.State,
                            ZIP = location.ZIP
                        };
                        context.WageLocations.Add(wageLocation);
                        context.SaveChanges();
                    }

                    else
                    {
                        WageLocation wageLocation = new WageLocation
                        {
                            Wage = FedMinimumWage,
                            LocationID = location.ID,
                            LocationName = location.Name,
                            Address = location.Address,
                            City = location.City,
                            County = location.County,
                            State = location.State,
                            ZIP = location.ZIP

                        };
                        context.WageLocations.Add(wageLocation);
                        context.SaveChanges();
                    }
                }
            }
            // Gathers the updated join table and populates the view model
            List<WageLocation> wageLocations = context.WageLocations.ToList();
            ViewLocationsViewModel viewLocationsViewModel = new ViewLocationsViewModel
            {
                WageLocations = wageLocations
            };
            return View(viewLocationsViewModel);
        }

        public IActionResult AddLocation()
        {
            AddLocationViewModel addLocationViewModel = new AddLocationViewModel();
            return View(addLocationViewModel);
        }    

        [HttpPost]
        public IActionResult AddLocation(AddLocationViewModel addLocationViewModel)
        {
            if (ModelState.IsValid)
            {
                Location newlocation = new Location
                {
                    Name = addLocationViewModel.Name.ToUpper(),
                    Address = addLocationViewModel.Address.ToUpper(),

FinalProject/Views/Location/AddLocation.cshtml
@model FinalProject.ViewModels.AddLocationViewModel

@{
    ViewData["Title"] = "View";
}


<h4>Add Individual Location</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddLocation" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select asp-for="State">
                    @foreach (string state in Model.states)
                    {
                        <option value="@state">@state</option>
                    }
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZIP" class="control-label"></label>
                <input asp-for="ZIP" class="form-control" />
                <span asp-validation-for="ZIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add New Location" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<hr />
<br />
<div>
    <form asp-controller="Location" asp-action="ImportCSV">
        <input type="submit" class="btn btn-primary" value="Import Multiple Locations with File Upload"/>
    </form>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

FinalProject/Views/Location/CSVSpecs.cshtml
@{
    ViewData["Title"] = "CSVSpecs";
}

<h1>CSV File Specifications</h1>

<p>Please Upload a CSV file with no Column Headers</p>
<br />
<table>
    <tr>
        <th>Column 1</th>
        <td>System number and Name <em>(e.g. 2000000 - Example)</em></td>
    </tr>
    <tr>
        <th>Column 2</th>
        <td>Address, including Ste Number</td>
    </tr>
    <tr>
        <th>Column 3</th>
        <td>City</td>
    </tr>
    <tr>
        <th>Column 4</th>
        <td>State</td>
    </tr>
    <tr>
        <th>Column 5</th>
        <td>5 digit ZIP code</td>
    </tr>
</table>
<br />
<br />
<form asp-controller="Location" asp-action="AddLocation">
    <input type="submit" class="btn btn-primary" value="Back to Add Location"/>
</form>

FinalProject/Views/Location/EditLocation.cshtml
@model FinalProject.ViewModels.ViewSingleLocationViewModel

@{
    ViewData["Title"] = "EditDeleteLocation";
}

<h1>EditDeleteLocation</h1>

<h4>ViewSingleLocationViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditLocation" method="post">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@Model.Name"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" value="@Model.Address" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" value="@Model.City" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label"></label>
                <input asp-for="County" class="form-control" value="@Model.County" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select>
                    @foreach (string state in Model.states)
                    {
                        <option value="@state">@state</option>
                    }
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZIP" class="control-label"></label>
                <input asp-for="ZIP" class="form-control" value="@Model.ZIP"/>
                <span asp-validation-for="ZIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FinalProject/Views/Location/ImportCSV.cshtml
@model FinalProject.ViewModels.UploadFileViewModel

@{
    ViewData["Title"] = "UploadCSV";
}



<h4>Upload Multiple Locations with CSV</h4>
<hr />
<p>For CSV File Specifications, see <a asp-controller="Location" asp-action="CSVSpecs">here.</a></p>
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="ImportCSV">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="file" />
            <span asp-validation-for="file"></span>
            <div class="form-group">
                <input type="submit" value="Upload File" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="text-danger">
@ViewBag.Message
    </div>
<div>
    <a asp-controller="location" asp-action="AddLocation">Add Individual Location</a>
</div>

FinalProject/Views/Location/Index.cshtml
@model FinalProject.ViewModels.ViewLocationsViewModel
@{
    ViewData["Title"] = "All Locations";
}

<h1>All Locations</h1>
<br />
<form asp-controller="location" asp-action="addlocation" method="post"><input type="submit" class="btn-primary" value="Add Location" /></form>
<br />
<form asp-controller="Location" asp-action="Export">
    <input type="submit" class="btn-primary" value="Export to CSV" />
</form>

<br />
<table class="table-striped">
    <tr>
        <th><a asp-controller="Location" asp-action="SortByMW">Minimum Wage</a></th>
        <th><a asp-controller="Location" asp-action="SortByLocationName">Location Name</a></th>
        <th><a asp-controller="Location" asp-action="SortByAddress">Address</a></th>
        <th><a asp-controller="Location" asp-action="SortByCity">City</a></th>
        <th><a asp-controller="Location" asp-action="SortByCounty">County</a></th>
        <th><a asp-controller="Location" asp-action="SortByState">State</a></th>
        <th><a asp-controller="Location" asp-action="SortByZIP">ZIP</a></th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

    @foreach (var location in Model.WageLocations)
    {
        <tr>
            <td>$@location.Wage</td>
            <td>@location.LocationName</td>
            <td>@location.Address</td>
            <td>@location.City</td>
            <td>@location.County</td>
            <td>@location.State</td>
            <td>@location.ZIP</td>
            <td><form asp-controller="location" asp-action="EditLocation" asp-route-id="@location.LocationID" method="post"><input type="submit" value="Edit" class="btn-secondary" /></form></td>
            <td><form asp-controller="Location" asp-action="DeleteLocation" asp-route-id="@location.LocationID " method="post"><input type="submit" value="Delete" class="btn-secondary" /></form></td>
        </tr>
    }
</table>