FinalProject/Models/Wage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.Models
{
    public class Wage
    {
        public int ID { get; set; }
        public DateTime EffectiveDate { get; set; }
        public decimal MinWage { get; set; }
    }
}

FinalProject/ViewModels/AddCityWageViewModel.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.ViewModels
{
    public class AddCityWageViewModel : StatesListViewModel
    {
        [Required(ErrorMessage = "Please Enter the City Name")]
        public string City  { get; set; }

        [Required(ErrorMessage = "Please Enter the full State name")]
        [StringLengthAttribute(50, MinimumLength = 3, ErrorMessage = "Please enter the full state name")]
        public string State { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public decimal MinWage { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime EffectiveDate { get; set; }

        public AddCityWageViewModel() { }


    }
}

FinalProject/ViewModels/AddCountyWageViewModel.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.ViewModels
{
    public class AddCountyWageViewModel : StatesListViewModel
    {
        [Required(ErrorMessage="Please enter the county name")]
        public string County { get; set; }

        [Required(ErrorMessage = "Please Enter the full State name")]
        [StringLengthAttribute(50, MinimumLength = 3,ErrorMessage = "Please enter the full state name")]
        public string State { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public decimal MinWage { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime EffectiveDate { get; set; }
    }
}

FinalProject/ViewModels/AddStateWageViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject.ViewModels
{
    public class AddStateWageViewModel : StatesListViewModel
    {
        [Required(ErrorMessage = "Please enter the minimum wage")]
        [DataType(DataType.Currency)]
        public decimal MinWage { get; set; }

        
        [Required (ErrorMessage="Please Select a State")]
        [StringLengthAttribute(50, MinimumLength = 3, ErrorMessage = "Please enter the full state name")]
        public string State { get; set; }

        [Required (ErrorMessage = "Please enter a valid date")]
        [DataType(DataType.Date)]
        public DateTime EffectiveDate { get; set; }

        public AddStateWageViewModel() { }

    }
}

FinalProject/Controllers/WageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Data;
using FinalProject.Models;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{   [Authorize]
    public class WageController : Controller
    {
        private readonly ApplicationDbContext context;

        public WageController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            List<StateWage> stateWages = context.StateWages.OrderBy(sw => sw.State).ToList();
            return View(stateWages);
        }
        public IActionResult CityWages()
        {
            List < CityWage > cityWages = context.CityWages.ToList();
            return View(cityWages);
        }
        public IActionResult AddStateWage()
        {

            AddStateWageViewModel addStateWageViewModel = new AddStateWageViewModel();
            return View(addStateWageViewModel);
 
        }

        [HttpPost]
        public IActionResult AddStateWage(AddStateWageViewModel addStateWageViewModel)
        {
            if (ModelState.IsValid)
            {
                StateWage newStateWage = new StateWage { 
                    MinWage = addStateWageViewModel.MinWage,
                    State = addStateWageViewModel.State,
                    EffectiveDate = addStateWageViewModel.EffectiveDate
                };

                context.Add(newStateWage);
                context.SaveChanges();

                return Redirect("/Wage/Index");
            }

            return View(addStateWageViewModel);
        }

       public IActionResult AddCityWage()
        {
            AddCityWageViewModel addCityWageViewModel = new AddCityWageViewModel();
            return View(addCityWageViewModel);
        }
        [HttpPost]
        public IActionResult AddCityWage(AddCityWageViewModel addCityWageViewModel)
        {
            if (ModelState.IsValid)
            {
                CityWage newCityWage = new CityWage
                {
                    MinWage = addCityWageViewModel.MinWage,
                    City = addCityWageViewModel.City,
                    State = addCityWageViewModel.State,
                    EffectiveDate = addCityWageViewModel.EffectiveDate
                };

                context.Add(newCityWage);
                context.SaveChanges();

                return Redirect("/Wage/SeeCityCountyWage?state=" + addCityWageViewModel.State.ToString());
            }

            return View(addCityWageViewModel);
        }

        public IActionResult AddCountyWage()
        {
            AddCountyWageViewModel addCountyWageViewModel = new AddCountyWageViewModel();
            return View(addCountyWageViewModel); 
        }

        [HttpPost]
        public IActionResult AddCountyWage(AddCountyWageViewModel addCountyWageViewModel)
        {
            if (ModelState.IsValid)
            {
                CountyWage newCountyWage = new CountyWage {
                    County = addCountyWageViewModel.County,
                    State = addCountyWageViewModel.State,
                    MinWage = addCountyWageViewModel.MinWage,
                    EffectiveDate = addCountyWageViewModel.EffectiveDate
                };
                context.Add(newCountyWage);
                context.SaveChanges();

                return Redirect("/Wage/SeeCityCountyWage?state=" + addCountyWageViewModel.State.ToString());
            }

            return View(addCountyWageViewModel);
        }
       
        public IActionResult SeeCityCountyWage (string state)
        {
           
            List<CityWage> cityWages = context.CityWages.Where(cw => cw.State == state).ToList();
            List<CountyWage> countyWages = context.CountyWages.Where(ctw => ctw.State == state).ToList();

            ViewCityCountyWagesViewModel viewCityCountyWagesViewModel = new ViewCityCountyWagesViewModel
            {
                CityWage = cityWages,
                CountyWage = countyWages
            };

            return View(viewCityCountyWagesViewModel);
        }

        public IActionResult DeleteStateWage (int ID)
        {
            StateWage stateWage = context.StateWages.Single(sw => sw.ID == ID);
            context.Remove(stateWage);
            context.SaveChanges();

            return Redirect("/Wage/Index");
        }

        public IActionResult EditStateWage(int ID)
        {
            StateWage stateWage = context.StateWages.Single(sw => sw.ID == ID);
            return View(stateWage);
        }

        [HttpPost]
        public IActionResult EditStateWage(AddStateWageViewModel addStateWageViewModel, int ID)
        {
            if (ModelState.IsValid)
            {
                StateWage stateWage = context.StateWages.Single(sw => sw.ID == ID);
                stateWage.MinWage = addStateWageViewModel.MinWage;
                stateWage.EffectiveDate = addStateWageViewModel.EffectiveDate;
                stateWage.State = addStateWageViewModel.State;
                context.SaveChanges();

                return Redirect("/Wage/Index");
            }
            return View(addStateWageViewModel);
        }

        public IActionResult DeleteCityWage (int ID)
        {
            CityWage cityWage = context.CityWages.Single(cw => cw.ID == ID);
            context.Remove(cityWage);
            context.SaveChanges();

            return Redirect("/Wage/SeeCityCountyWage?state=" + cityWage.State.ToString());
        }

        public IActionResult DeleteCountyWage (int ID)
        {
            CountyWage countyWage = context.CountyWages.Single(ctw => ctw.ID == ID);
            context.Remove(countyWage);
            context.SaveChanges();

            return Redirect("/Wage/SeeCityCountyWage?state=" + countyWage.State.ToString());
        }

        public IActionResult EditCityWage(int ID)
        {
            CityWage cityWage = context.CityWages.Single(cw => cw.ID == ID);
            return View(cityWage);
        }
        [HttpPost]
        public IActionResult EditCityWage(AddCityWageViewModel addCityWageViewModel, int ID)
        {
            if (ModelState.IsValid)
            {
                CityWage cityWage = context.CityWages.Single(cw => cw.ID == ID);
                cityWage.City = addCityWageViewModel.City;
                cityWage.State = addCityWageViewModel.State;
                cityWage.EffectiveDate = addCityWageViewModel.EffectiveDate;
                cityWage.MinWage = addCityWageViewModel.MinWage;

                context.SaveChanges();

                return Redirect("Wage/SeeCityCountyWage?state=" + cityWage.State.ToString());
            }
            return View(addCityWageViewModel);
        }

        public IActionResult EditCountyWage(int ID)
        {
            CountyWage countyWage = context.CountyWages.Single(ctw => ctw.ID == ID);
            return View(countyWage);
        }

        [HttpPost]
        public IActionResult EditCountyWage(AddCountyWageViewModel addCountyWageViewModel, int ID)
        {
            if (ModelState.IsValid) 
            { 
                CountyWage countyWage = context.CountyWages.Single(ctw => ctw.ID == ID);
                countyWage.County = addCountyWageViewModel.County;
                countyWage.State = addCountyWageViewModel.State;
                countyWage.EffectiveDate = addCountyWageViewModel.EffectiveDate;
                countyWage.MinWage = addCountyWageViewModel.MinWage;

                context.SaveChanges();
                return Redirect("/Wage/SeeCityCountyWage?state=" + countyWage.State.ToString());
            }
            return View(addCountyWageViewModel);


        }
    }
}

FinalProject/Views/Wage/AddCityWage.cshtml
@model FinalProject.ViewModels.AddCityWageViewModel

@{
    ViewData["Title"] = "AddCityWage";
}

<h1>AddCityWage</h1>

<h4>CityWage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCityWage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select asp-for="State">
                    @foreach(string state in Model.states)
                    {
                    <option value="@state">@state</option>
                    }
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinWage" class="control-label"></label>
                <input asp-for="MinWage" class="form-control" />
                <span asp-validation-for="MinWage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveDate" class="control-label"></label>
                <input asp-for="EffectiveDate" class="form-control" />
                <span asp-validation-for="EffectiveDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add New City Wage" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FinalProject/Views/Wage/AddCountyWage.cshtml
@model FinalProject.ViewModels.AddCountyWageViewModel

@{
    ViewData["Title"] = "AddCountyWage";
}

<h1>AddCountyWage</h1>

<h4>AddCountyWageViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCountyWage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="County" class="control-label"></label>
                <input asp-for="County" class="form-control" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select asp-for="State">
                    @foreach(string state in Model.states)
                    {
                        <option value="@state">@state</option>
                    }
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinWage" class="control-label"></label>
                <input asp-for="MinWage" class="form-control" />
                <span asp-validation-for="MinWage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveDate" class="control-label"></label>
                <input asp-for="EffectiveDate" class="form-control" />
                <span asp-validation-for="EffectiveDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add County Wage" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FinalProject/Views/Wage/AddStateWage.cshtml
@model FinalProject.ViewModels.AddStateWageViewModel

@{
    ViewData["Title"] = "View";

   
}

<h1>View</h1>

<h4>AddStateWageViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddStateWage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MinWage" class="control-label"></label>
                <input asp-for="MinWage" class="form-control" />
                <span asp-validation-for="MinWage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select asp-for="State">
                    @foreach(string state in Model.states) 
                    {
                        <option value="@state">@state</option>
                    }
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveDate" class="control-label"></label>
                <input asp-for="EffectiveDate" class="form-control" />
                <span asp-validation-for="EffectiveDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add New State Wage" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

FinalProject/Views/Wage/EditCityWage.cshtml
@model FinalProject.ViewModels.AddCityWageViewModel

@{
    ViewData["Title"] = "EditCityWage";
}

<h1>EditCityWage</h1>

<h4>AddCityWageViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCityWage" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select asp-for="State">
                    @foreach (string state in Model.states)
                    {
                    <option value="@state">@state</option>
                    }
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinWage" class="control-label"></label>
                <input asp-for="MinWage" class="form-control" />
                <span asp-validation-for="MinWage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveDate" class="control-label"></label>
                <input asp-for="EffectiveDate" class="form-control" />
                <span asp-validation-for="EffectiveDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FinalProject/Views/Wage/EditStateWage.cshtml
@model FinalProject.ViewModels.AddStateWageViewModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>AddStateWageViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditStateWage">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MinWage" class="control-label"></label>
                <input asp-for="MinWage" class="form-control" />
                <span asp-validation-for="MinWage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <select asp-for="State">
                    @foreach (string state in Model.states)
                    {
                        <option value="@state">@state</option>
                    }
                </select>
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EffectiveDate" class="control-label"></label>
                <input asp-for="EffectiveDate" class="form-control" />
                <span asp-validation-for="EffectiveDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FinalProject/Views/Wage/Index.cshtml
@model List<FinalProject.Models.StateWage>;
@{
    ViewData["Title"] = "Index";
}

<h1>State Minimum Wages</h1>
<form asp-controller="Wage" asp-action="AddStateWage"><input class="btn-primary"type="submit" value="Add New State Wage"/></form>
<table>
    <tr>
        <th>State</th>
        <th>Minimum Wage</th>
        <th>Effective Date</th>
        <th>Cities</th>
        <th>Edit</th>
        <th>Delete</th>

    </tr>
    @foreach (var wage in Model)
    {
        <tr>
            <td>@wage.State</td>
            <td>$@wage.MinWage</td>
            <td>@wage.EffectiveDate</td>
            <td><a asp-controller="wage" asp-action="SeeCityCountyWage" asp-route-state="@wage.State">See City Minimum Wages for @wage.State</a></td>
            <td><form asp-controller="wage" asp-action="EditStateWage" asp-route-id="@wage.ID"><input value="Edit" type="submit" class="btn-secondary"/></form></td>
            <td><form asp-controller="wage" asp-action="DeleteStateWage" asp-route-id="@wage.ID"><input value="Delete" type="submit" class="btn-secondary"/></form></td>
        </tr>
    }
</table>

FinalProject/Views/Wage/SeeCityCountyWage.cshtml
@model FinalProject.ViewModels.ViewCityCountyWagesViewModel;
@{
    ViewData["Title"] = "See City and County Minimum Wages";
}

<h1>See City and County Minimum Wages</h1>
<div>
    <form asp-controller="Wage" asp-action="AddCityWage" method="post"><input type="submit" class="btn-primary" value="Add New City Wage" /></form>
    <form asp-controller="Wage" asp-action="AddCountyWage" method="post"><input type="submit" class="btn-primary" value="Add New County Wage" /></form>
</div>
<div>
    <h3>City Minimum Wages</h3>
    <table class="table-striped">
        <tr>
            <th>City Name</th>
            <th>State Name</th>
            <th>Minimum Wage</th>
            <th>Effective Date</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
      
            @foreach (var city in Model.CityWage)
            {
             <tr>
                <td>@city.City</td>
                <td>@city.State</td>
                <td>$@city.MinWage</td>
                <td>@city.EffectiveDate</td>
                <td><form asp-controller="Wage" asp-action="EditCityWage" asp-route-id="@city.ID"><input type="submit" value="Edit" class="btn-secondary"/></form></td>
                 <td><form asp-controller="Wage" asp-action="DeleteCityWage" asp-route-id="@city.ID"><input type="submit" value="Delete" class="btn-secondary"/></form></td>
            </tr>
            }
 
    </table>
</div>
<div>
    <h3>County Minimum Wages</h3>
    <table class="table-striped">
        <tr>
            <th>County Name</th>
            <th>State Name</th>
            <th>Minimum Wage</th>
            <th>Effective Date</th>
            <th>Edit</th>
            <th>Delete</th>

        </tr>
        <tr>
            @foreach (var county in Model.CountyWage)
            {
                <td>@county.County</td>
                <td>@county.State</td>
                <td>$@county.MinWage</td>
                <td>@county.EffectiveDate</td>
                <td><form asp-controller="Wage" asp-action="EditCountyWage" asp-route-id="@county.ID"><input type="submit" value="Edit" class="btn-secondary" /></form></td>
                <td><form asp-controller="Wage" asp-action="DeleteCountyWage" asp-route-id="@county.ID"><input type="submit" value="Delete" class="btn-secondary" /></form></td>
            }
        </tr>
    </table>
</div>